config/routes.rb
EmployeeTool::Application.routes.draw do
  devise_for :employees

  devise_for :employees, :path => '', path_names: {sign_in: "login", sign_out: "logout"}
  resources :companies, :only => [:show] do
    resources :employees, :only => [:index, :show]
  end

  root to: "employees#show"
end

app/models/absence.rb
class Absence < ActiveRecord::Base
  attr_accessible :date_filed, :department_id, :employee_id, :end_date, :leave_type_id, :reasons, :start_date, :status, :total_hours

  validates :date_filed, :presence => true
  validates :employee_id, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :leave_type_id, :presence => true
  validates :reasons, :presence => true
  validates :status, :presence => true
  validates :total_hours, :presence => true

  belongs_to :leave_type
  belongs_to :employee
  belongs_to :department

  before_create :set_status
  after_create :deduct_leave_credit

  def deduct_leave_credit
    leave_credit = self.employee.leave_credits.where(:leave_type_id => self.leave_type_id).first
    leave_credit.update_attribute(:count, leave_credit.count -= self.employee.translate_hours(self.total_hours) )
  end

  def set_status
    self.status = "pending"
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :business_address, :business_phone, :date_founded, :fax_number, :full_name, :slug, :status

  validates :business_address, :presence => true
  validates :business_phone, :presence => true
  validates :date_founded, :presence => true
  validates :full_name, :presence => true

  validates :full_name, :uniqueness => true

  has_many :employees, :dependent => :destroy
  has_many :departments, :dependent => :destroy

  def is_employee?(employee)
    self.employees.include?(employee)
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :department_head_id, :name

  validates :name, :presence => true
  validates :name, :uniqueness => true

  has_many :employees
  has_many :absences, :dependent => :destroy

  belongs_to :company
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :address, :civil_status, :date_of_birth,
                  :emergency_contact, :first_name, :gender,
                  :last_name,
                  :level, :middle_name,
                  :mobile_number, :pagibig, :philhealth, :telephone_number, :tin

  #validations

  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true
  validates :first_name, :presence => true
  validates :middle_name, :presence => true
  validates :last_name, :presence => true
  validates :address, :presence => true
  validates :civil_status, :presence => true
  validates :date_of_birth, :presence => true
  validates_uniqueness_of :first_name, :scope => [:middle_name, :last_name]

  has_many :absences, :dependent => :destroy
  has_many :leave_credits, :dependent => :destroy

  belongs_to :company
  belongs_to :department

  def name
    self.first_name + " " + self.last_name
  end

  def sick_leaves
    leave = self.leave_credits.joins(:leave_type).where(:leave_types => {:name => "Sick Leave"}).first
    leave.nil? ? 0 : leave.count
  end

  def vacation_leaves
    leave = self.leave_credits.find_by_leave_type_id(2)
    leave.nil? ? 0 : leave.count
  end

  def file_absence(leave_type_id,date_filed,start_date,end_date,total_hours,reasons)
    leave_type = LeaveType.find(leave_type_id)
    return "You do not have enough #{leave_type.name} credits." unless self.leave_credits.map(&:leave_type_id).include?(leave_type_id) && self.has_enough_leave_credit_balance?(leave_type_id, total_hours)
    absence = self.absences.new(:department_id => self.department,
                         :leave_type_id => leave_type_id,
                         :date_filed => date_filed,
                         :start_date => start_date,
                         :end_date => end_date,
                         :total_hours => total_hours,
                         :reasons => reasons)

    absence.save! if absence.valid?
  end

  def has_enough_leave_credit_balance?(leave_type_id, desired_credit_count)
    credit = self.leave_credits.find_by_leave_type_id(leave_type_id)

    #return false unless credit

    credit.count < desired_credit_count || credit.nil? ? false : true
  end

  def translate_hours(total_hours)
    total_hours / 8
  end
end

app/models/leave_credit.rb
class LeaveCredit < ActiveRecord::Base
  attr_accessible :count, :employee_id, :leave_type_id

  validates :count, :presence => true
  validates :employee_id, :presence => true
  validates :leave_type_id, :presence => true
  validates_uniqueness_of :employee_id, :scope => :leave_type_id

  belongs_to :employee
  belongs_to :leave_type
end

app/models/leave_type.rb
class LeaveType < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, :presence => true
  validates :name, :uniqueness => true

  has_many :leave_credits, :dependent => :destroy
  has_many :absences, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :authenticate_employee!

  def index
    @company = current_employee.company
    @employees = @company.employees
  end

  def show
    if params[:id]
    else
      @employee = current_employee
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def panel(class_name, value, label, link)
     render :partial => "panel_view", :locals => { :class_name => class_name, :value => value, :label => label, :link => link }
  end
end

app/views/employees/_panel_view.html.erb
<div class="col-lg-3">
  <div class="panel <%= class_name.html_safe %>">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-6">
          <i class="fa fa-comments fa-5x"></i>
        </div>
        <div class="col-xs-6 text-right">
          <p class="announcement-heading"><%= value %></p>
          <p class="announcement-text"><%= label %>!</p>
        </div>
      </div>
    </div>
    <a href="#">
      <div class="panel-footer announcement-bottom">
        <div class="row">
          <div class="col-xs-6">
            <%= link %>
          </div>
          <div class="col-xs-6 text-right">
            <i class="fa fa-arrow-circle-right"></i>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>

app/views/employees/index.html.erb
<div id="container">
  <h1 class="page-header"><%= current_employee.company.full_name %></h1>
  <% if @employees.empty? %>
    <i> No employees found </i>
  <% else %>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                  Employee List
                </div>
            <!-- /.panel-heading -->
              <% @employees.each do |employee| %>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                  <th>Name</th>
                                  <th>Department</th>
                                  <th>Level</th>
                                  <th>Sick Leaves</th>
                                  <th>Vacation Leaves</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX">
                                  <td><%= link_to employee.name, company_employee_path(employee.company, employee) %></td>
                                  <td><%= employee.department.name %></td>
                                  <td><%= employee.level %></td>
                                  <td><%= employee.sick_leaves %></td>
                                  <td><%= employee.vacation_leaves %></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
              <% end %>
            </div>
        </div>
    </div>
  <% end %>
</div>

app/views/employees/show.html.erb
<div id="container">
  <h1 class="page-header"><%= current_employee.name %></h1>
  <div class="row">
    <%= panel("panel-info", current_employee.sick_leaves, "Sick Leaves left", "File Sick Leave")%>
    <%= panel("panel-success", current_employee.vacation_leaves, "Vacation Leaves left", "File Vacation Leave")%>
  </div><!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Leaves
        </div>
        <!-- /.panel-heading -->
            <div class="panel-body">
              <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                  <thead>
                  <tr>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Status</th>
                    <th>Reason</th>
                    <th>Total Hours</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% current_employee.absences.each do |absence| %>
                      <tr class="odd gradeX">
                        <td><%= absence.start_date %></td>
                        <td><%= absence.end_date %></td>
                        <td><%= absence.status %></td>
                        <td><%= absence.reasons %></td>
                        <td><%= absence.total_hours %></td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smart Tracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="wrapper">

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<a class="navbar-brand" href="index.html">Smart Tracker</a>-->
          <%= link_to "Smart Tracker", root_path, :class => "navbar-brand" %>
        </div>

          <% if employee_signed_in? %>
            <ul class="nav navbar-top-links navbar-right">
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <%= current_employee.first_name %>  <i class="fa fa-caret-down"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <!--<li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>-->
                    <li><%= link_to destroy_employee_session_path, :method => :delete do %>
                          <i class="fa fa-sign-out fa-fw"></i> Logout
                        <% end %>
                    </li>
                  </ul>
                </li>
            </ul>
            <div class="navbar-default navbar-static-side" role="navigation">
              <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                  <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                      <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                  <i class="fa fa-search"></i>
                                </button>
                            </span>
                    </div>
                    <!-- /input-group -->
                  </li>
                  <li>
                    <%= link_to(root_path) do%>
                        <i class="fa fa-dashboard fa-fw"></i> Dashboard
                  <% end %>
                  </li>
                </ul>
              </div>
            </div>
        <% end %>
      </nav>
      <% if employee_signed_in? %>
      <div id="page-wrapper">
        <div class="row">
          <div class="col-lg-12">
            <%= yield %>
          </div>
          <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
      </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
</body>
</html>